name:                davl-cli
version:             0.1.0.0
description:         CLI for the DAVL holiday tracking application, driven by DAML.
license:             Apache-2.0
author:              The DAVL authors
maintainer:          nick.chapman@digitalasset.com
github:              https://github.com/digital-asset/davl

dependencies:
- ansi-terminal
- bytestring
- base >= 4.7 && < 5
- containers
- daml-ledger
- extra
- haskeline
- random
- text
- transformers
- uuid
- utility-ht

executables:
  davl-cli:
    main:                Davl.Main
    source-dirs:         src
    ghc-options:
    - -Wall
    - -Wno-name-shadowing
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

    default-extensions:
    - DuplicateRecordFields
    - LambdaCase
    - NamedFieldPuns
    - OverloadedStrings
    - RecordWildCards
    - ScopedTypeVariables
